global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Node Exporter (system metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'localhost:9100' ]

  # Lucecis App metrics
  - job_name: 'lucecis-metrics-server'
    static_configs:
      - targets: [ 'localhost:3020' ]
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Health checks using blackbox_exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://localhost:3000/lucecis/health  # NextJS web server health endpoint
          - http://localhost:3020/health  # WebSocket server health endpoint (via HTTP metrics server)
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9110  # blackbox_exporter address
  # Blackbox_exporter itself
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: [ '127.0.0.1:9110' ]