global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Node Exporter (system metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'localhost:9100' ]

  # Lucecis App metrics
  - job_name: 'lucecis-metrics-server'
    static_configs:
      - targets: [ 'localhost:3020' ]
    metrics_path: '/metrics'
    scrape_interval: 5s